// Write a function that takes in a string and removes ALL vowels (a, e, i, o, u).
// Try to make this work to remove all vowels regardless of case...
// HINT: If you're looking to learn something new, try using a JavaScript regex!